boot.o: boot.S multiboot.h x86_desc.h types.h
idt_linkage.o: idt_linkage.S
paging.o: paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
handler.o: handler.c lib.h types.h i8259.h rtc.h kb.h
i8259.o: i8259.c i8259.h types.h lib.h
kb.o: kb.c kb.h types.h lib.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt_linkage.h handler.h rtc.h kb.h paging.h
lib.o: lib.c lib.h types.h
paging.o: paging.c
rtc.o: rtc.c lib.h types.h rtc.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
